from __future__ import annotations

import json
from dataclasses import dataclass
from typing import Any

from text2ql.schema_config import NormalizedSchemaConfig


@dataclass(slots=True)
class GraphQLIntent:
    entity: str
    fields: list[str]
    filters: dict[str, str]
    explanation: str
    confidence: float


class ConstrainedOutputError(ValueError):
    """Raised when LLM output fails schema validation."""


def parse_graphql_intent(raw: str, config: NormalizedSchemaConfig) -> GraphQLIntent:
    try:
        payload = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise ConstrainedOutputError("LLM output must be valid JSON") from exc

    if not isinstance(payload, dict):
        raise ConstrainedOutputError("LLM output must be a JSON object")

    entity = payload.get("entity")
    fields = payload.get("fields")
    filters = payload.get("filters", {})
    explanation = payload.get("explanation", "Generated by LLM mode.")
    confidence = payload.get("confidence", 0.5)

    if not isinstance(entity, str) or not entity.strip():
        raise ConstrainedOutputError("Field 'entity' must be a non-empty string")
    if not isinstance(fields, list) or not all(isinstance(v, str) and v.strip() for v in fields):
        raise ConstrainedOutputError("Field 'fields' must be a list of non-empty strings")
    if not isinstance(filters, dict):
        raise ConstrainedOutputError("Field 'filters' must be an object")
    if not isinstance(explanation, str):
        raise ConstrainedOutputError("Field 'explanation' must be a string")
    if not isinstance(confidence, (int, float)):
        raise ConstrainedOutputError("Field 'confidence' must be a number")

    canonical_entity = _canonicalize_entity(entity.strip(), config)
    canonical_fields = [_canonicalize_field(field.strip(), config) for field in fields]
    canonical_filters = {
        _canonicalize_filter_key(str(key), config): _canonicalize_filter_value(
            _canonicalize_filter_key(str(key), config), value, config
        )
        for key, value in filters.items()
    }

    normalized_confidence = max(0.0, min(1.0, float(confidence)))
    return GraphQLIntent(
        entity=canonical_entity,
        fields=_dedupe(canonical_fields),
        filters=canonical_filters,
        explanation=explanation,
        confidence=normalized_confidence,
    )


def _canonicalize_entity(entity: str, config: NormalizedSchemaConfig) -> str:
    lower = entity.lower()
    if lower in config.entity_aliases:
        return config.entity_aliases[lower]
    if config.entities and entity not in config.entities:
        if config.default_entity:
            return config.default_entity
    return entity


def _canonicalize_field(field: str, config: NormalizedSchemaConfig) -> str:
    lower = field.lower()
    if lower in config.field_aliases:
        return config.field_aliases[lower]
    return field


def _canonicalize_filter_key(key: str, config: NormalizedSchemaConfig) -> str:
    lower = key.lower()
    if lower in config.filter_key_aliases:
        return config.filter_key_aliases[lower]
    return key


def _canonicalize_filter_value(
    key: str, value: Any, config: NormalizedSchemaConfig
) -> str:
    string_value = str(value)
    key_aliases = config.filter_value_aliases.get(key.lower(), {})
    return key_aliases.get(string_value.lower(), string_value)


def _dedupe(items: list[str]) -> list[str]:
    seen: set[str] = set()
    out: list[str] = []
    for item in items:
        if item in seen:
            continue
        seen.add(item)
        out.append(item)
    return out
