from __future__ import annotations

import json
import re
from dataclasses import dataclass
from typing import Any

from text2ql.prompting import resolve_language
from text2ql.schema_config import NormalizedSchemaConfig


@dataclass(slots=True)
class GraphQLIntent:
    entity: str
    fields: list[str]
    filters: dict[str, str]
    explanation: str
    confidence: float


@dataclass(slots=True)
class SQLIntent:
    table: str
    columns: list[str]
    filters: dict[str, Any]
    joins: list[dict[str, Any]]
    order_by: str | None
    order_dir: str | None
    limit: int | None
    offset: int | None
    explanation: str
    confidence: float


class ConstrainedOutputError(ValueError):
    """Raised when LLM output fails schema validation."""


def parse_graphql_intent(
    raw: str, config: NormalizedSchemaConfig, language: str = "english"
) -> GraphQLIntent:
    resolved_language = resolve_language(language)
    if resolved_language != "english":
        raise ConstrainedOutputError(f"Unsupported constraint language '{language}'")

    payload = _load_intent_payload(raw)

    if not isinstance(payload, dict):
        raise ConstrainedOutputError("LLM output must be a JSON object")

    entity = payload.get("entity")
    fields = payload.get("fields")
    filters = payload.get("filters", {})
    explanation = payload.get("explanation", "Generated by LLM mode.")
    confidence = payload.get("confidence", 0.5)

    if not isinstance(entity, str) or not entity.strip():
        raise ConstrainedOutputError("Field 'entity' must be a non-empty string")
    if not isinstance(fields, list) or not all(isinstance(v, str) and v.strip() for v in fields):
        raise ConstrainedOutputError("Field 'fields' must be a list of non-empty strings")
    if not isinstance(filters, dict):
        raise ConstrainedOutputError("Field 'filters' must be an object")
    if not isinstance(explanation, str):
        raise ConstrainedOutputError("Field 'explanation' must be a string")
    if not isinstance(confidence, (int, float)):
        raise ConstrainedOutputError("Field 'confidence' must be a number")

    canonical_entity = _canonicalize_entity(entity.strip(), config)
    canonical_fields = [_canonicalize_field(field.strip(), config) for field in fields]
    canonical_filters = {
        _canonicalize_filter_key(str(key), config): _canonicalize_filter_value(
            _canonicalize_filter_key(str(key), config), value, config
        )
        for key, value in filters.items()
    }

    normalized_confidence = max(0.0, min(1.0, float(confidence)))
    return GraphQLIntent(
        entity=canonical_entity,
        fields=_dedupe(canonical_fields),
        filters=canonical_filters,
        explanation=explanation,
        confidence=normalized_confidence,
    )


def parse_sql_intent(
    raw: str, config: NormalizedSchemaConfig, language: str = "english"
) -> SQLIntent:
    resolved_language = resolve_language(language)
    if resolved_language != "english":
        raise ConstrainedOutputError(f"Unsupported constraint language '{language}'")

    payload = _load_intent_payload(raw)
    if not isinstance(payload, dict):
        raise ConstrainedOutputError("LLM output must be a JSON object")

    table = payload.get("table", payload.get("entity"))
    columns = payload.get("columns", payload.get("fields"))
    filters = payload.get("filters", {})
    joins = payload.get("joins", [])
    order_by = payload.get("order_by")
    order_dir = payload.get("order_dir")
    limit = payload.get("limit")
    offset = payload.get("offset")
    explanation = payload.get("explanation", "Generated by LLM mode.")
    confidence = payload.get("confidence", 0.5)

    if not isinstance(table, str) or not table.strip():
        raise ConstrainedOutputError("Field 'table' must be a non-empty string")
    if not isinstance(columns, list) or not all(isinstance(v, str) and v.strip() for v in columns):
        raise ConstrainedOutputError("Field 'columns' must be a list of non-empty strings")
    if not isinstance(filters, dict):
        raise ConstrainedOutputError("Field 'filters' must be an object")
    if not isinstance(joins, list):
        raise ConstrainedOutputError("Field 'joins' must be a list")
    if order_by is not None and not isinstance(order_by, str):
        raise ConstrainedOutputError("Field 'order_by' must be a string when provided")
    if order_dir is not None and not isinstance(order_dir, str):
        raise ConstrainedOutputError("Field 'order_dir' must be a string when provided")
    if limit is not None and not isinstance(limit, (int, float, str)):
        raise ConstrainedOutputError("Field 'limit' must be numeric/string when provided")
    if offset is not None and not isinstance(offset, (int, float, str)):
        raise ConstrainedOutputError("Field 'offset' must be numeric/string when provided")
    if not isinstance(explanation, str):
        raise ConstrainedOutputError("Field 'explanation' must be a string")
    if not isinstance(confidence, (int, float)):
        raise ConstrainedOutputError("Field 'confidence' must be a number")

    canonical_table = _canonicalize_entity(table.strip(), config)
    canonical_columns = [_canonicalize_field(column.strip(), config) for column in columns]
    canonical_filters = {
        _canonicalize_filter_key(str(key), config): _canonicalize_filter_value(
            _canonicalize_filter_key(str(key), config), value, config
        )
        for key, value in filters.items()
    }
    normalized_confidence = max(0.0, min(1.0, float(confidence)))
    normalized_limit = _coerce_optional_int(limit)
    normalized_offset = _coerce_optional_int(offset)
    normalized_order_dir = order_dir.upper() if isinstance(order_dir, str) else None
    if normalized_order_dir not in {None, "ASC", "DESC"}:
        normalized_order_dir = None

    return SQLIntent(
        table=canonical_table,
        columns=_dedupe(canonical_columns),
        filters=canonical_filters,
        joins=[join for join in joins if isinstance(join, dict)],
        order_by=order_by.strip() if isinstance(order_by, str) and order_by.strip() else None,
        order_dir=normalized_order_dir,
        limit=normalized_limit,
        offset=normalized_offset,
        explanation=explanation,
        confidence=normalized_confidence,
    )


def _canonicalize_entity(entity: str, config: NormalizedSchemaConfig) -> str:
    lower = entity.lower()
    if lower in config.entity_aliases:
        return config.entity_aliases[lower]
    if config.entities and entity not in config.entities:
        if config.default_entity:
            return config.default_entity
    return entity


def _canonicalize_field(field: str, config: NormalizedSchemaConfig) -> str:
    lower = field.lower()
    if lower in config.field_aliases:
        return config.field_aliases[lower]
    return field


def _canonicalize_filter_key(key: str, config: NormalizedSchemaConfig) -> str:
    lower = key.lower()
    if lower in config.filter_key_aliases:
        return config.filter_key_aliases[lower]
    return key


def _canonicalize_filter_value(
    key: str, value: Any, config: NormalizedSchemaConfig
) -> str:
    string_value = str(value)
    key_aliases = config.filter_value_aliases.get(key.lower(), {})
    return key_aliases.get(string_value.lower(), string_value)


def _dedupe(items: list[str]) -> list[str]:
    seen: set[str] = set()
    out: list[str] = []
    for item in items:
        if item in seen:
            continue
        seen.add(item)
        out.append(item)
    return out


def _coerce_optional_int(value: Any) -> int | None:
    if value is None:
        return None
    try:
        return int(value)
    except (TypeError, ValueError):
        return None


def _load_intent_payload(raw: str) -> dict[str, Any]:
    try:
        payload = json.loads(raw)
    except json.JSONDecodeError:
        payload = None
    if isinstance(payload, dict):
        return payload

    fenced = _extract_fenced_json(raw)
    if fenced is not None:
        try:
            payload = json.loads(fenced)
        except json.JSONDecodeError:
            payload = None
        if isinstance(payload, dict):
            return payload

    object_blob = _extract_first_json_object(raw)
    if object_blob is not None:
        try:
            payload = json.loads(object_blob)
        except json.JSONDecodeError:
            payload = None
        if isinstance(payload, dict):
            return payload

    raise ConstrainedOutputError("LLM output must be valid JSON")


def _extract_fenced_json(raw: str) -> str | None:
    # Non-greedy outer match captures only the FIRST fenced block; delegate to
    # _extract_first_json_object so nested braces are handled correctly instead
    # of the greedy {.*} pattern spanning across multiple code blocks.
    match = re.search(r"```(?:json)?\s*(.*?)\s*```", raw, flags=re.S | re.I)
    if not match:
        return None
    return _extract_first_json_object(match.group(1))


def _extract_first_json_object(raw: str) -> str | None:
    start = raw.find("{")
    if start < 0:
        return None
    depth = 0
    in_string = False
    escaped = False
    for idx in range(start, len(raw)):
        ch = raw[idx]
        if escaped:
            escaped = False
            continue
        if ch == "\\":
            escaped = True
            continue
        if ch == '"':
            in_string = not in_string
            continue
        if in_string:
            continue
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                return raw[start : idx + 1].strip()
    return None
