from __future__ import annotations

import json
import re
from dataclasses import dataclass
from typing import Any

from text2ql.prompting import resolve_language
from text2ql.schema_config import NormalizedSchemaConfig


@dataclass(slots=True)
class GraphQLIntent:
    entity: str
    fields: list[str]
    filters: dict[str, str]
    explanation: str
    confidence: float
    aggregations: list[dict]
    nested: list[dict]
    distinct: bool
    having: list[dict]


@dataclass(slots=True)
class SQLIntent:
    table: str
    columns: list[str]
    filters: dict[str, Any]
    joins: list[dict[str, Any]]
    order_by: str | None
    order_dir: str | None
    limit: int | None
    offset: int | None
    explanation: str
    confidence: float
    aggregations: list[dict]
    distinct: bool
    having: list[dict]
    subqueries: list[dict]


class ConstrainedOutputError(ValueError):
    """Raised when LLM output fails schema validation."""


def parse_graphql_intent(
    raw: str, config: NormalizedSchemaConfig, language: str = "english"
) -> GraphQLIntent:
    payload = _validated_intent_payload(raw, language)
    entity = _require_non_empty_str(payload.get("entity"), "Field 'entity' must be a non-empty string")
    fields = _require_non_empty_str_list(payload.get("fields"), "Field 'fields' must be a list of non-empty strings")
    filters = _require_dict(payload.get("filters", {}), "Field 'filters' must be an object")
    explanation = _require_str(payload.get("explanation", "Generated by LLM mode."), "Field 'explanation' must be a string")
    confidence = _require_number(payload.get("confidence", 0.5), "Field 'confidence' must be a number")

    aggregations = _normalize_intent_dict_list(payload.get("aggregations", []), required_keys={"function", "field"})
    nested = _normalize_intent_dict_list(payload.get("nested", []), required_keys={"relation"})
    distinct = bool(payload.get("distinct", False))
    having = _normalize_intent_dict_list(
        payload.get("having", []),
        required_keys={"function", "operator", "value"},
    )

    canonical_entity = _canonicalize_entity(entity.strip(), config)
    canonical_fields = [_canonicalize_field(field.strip(), config) for field in fields]
    canonical_filters = {
        _canonicalize_filter_key(str(key), config): _canonicalize_filter_value(
            _canonicalize_filter_key(str(key), config), value, config
        )
        for key, value in filters.items()
    }
    canonical_filters = _expand_operator_filter_dicts(canonical_filters)

    normalized_confidence = max(0.0, min(1.0, float(confidence)))
    return GraphQLIntent(
        entity=canonical_entity,
        fields=_dedupe(canonical_fields),
        filters=canonical_filters,
        explanation=explanation,
        confidence=normalized_confidence,
        aggregations=aggregations,
        nested=nested,
        distinct=distinct,
        having=having,
    )


def parse_sql_intent(
    raw: str, config: NormalizedSchemaConfig, language: str = "english"
) -> SQLIntent:
    payload = _validated_intent_payload(raw, language)
    table = payload.get("table", payload.get("entity"))
    columns = payload.get("columns", payload.get("fields"))
    filters = payload.get("filters", {})
    joins = payload.get("joins", [])
    order_by = payload.get("order_by")
    order_dir = payload.get("order_dir")
    limit = payload.get("limit")
    offset = payload.get("offset")
    explanation = payload.get("explanation", "Generated by LLM mode.")
    confidence = payload.get("confidence", 0.5)

    table = _require_non_empty_str(table, "Field 'table' must be a non-empty string")
    columns = _require_non_empty_str_list(columns, "Field 'columns' must be a list of non-empty strings")
    filters = _require_dict(filters, "Field 'filters' must be an object")
    joins = _require_list(joins, "Field 'joins' must be a list")
    _ensure_optional_str(order_by, "Field 'order_by' must be a string when provided")
    _ensure_optional_str(order_dir, "Field 'order_dir' must be a string when provided")
    _ensure_optional_scalar(limit, "Field 'limit' must be numeric/string when provided")
    _ensure_optional_scalar(offset, "Field 'offset' must be numeric/string when provided")
    explanation = _require_str(explanation, "Field 'explanation' must be a string")
    confidence = _require_number(confidence, "Field 'confidence' must be a number")

    aggregations = _normalize_intent_dict_list(payload.get("aggregations", []), required_keys={"function", "field"})
    distinct = bool(payload.get("distinct", False))
    having = _normalize_intent_dict_list(
        payload.get("having", []),
        required_keys={"function", "operator", "value"},
    )
    subqueries = _normalize_intent_dict_list(payload.get("subqueries", []), required_keys={"subquery_table"})

    canonical_table = _canonicalize_entity(table.strip(), config)
    canonical_columns = [_canonicalize_field(column.strip(), config) for column in columns]
    canonical_filters = {
        _canonicalize_filter_key(str(key), config): _canonicalize_filter_value(
            _canonicalize_filter_key(str(key), config), value, config
        )
        for key, value in filters.items()
    }
    canonical_filters = _expand_operator_filter_dicts(canonical_filters)
    normalized_confidence = max(0.0, min(1.0, float(confidence)))
    normalized_limit = _coerce_optional_int(limit)
    normalized_offset = _coerce_optional_int(offset)
    normalized_order_dir = order_dir.upper() if isinstance(order_dir, str) else None
    if normalized_order_dir not in {None, "ASC", "DESC"}:
        normalized_order_dir = None

    return SQLIntent(
        table=canonical_table,
        columns=_dedupe(canonical_columns),
        filters=canonical_filters,
        joins=[join for join in joins if isinstance(join, dict)],
        order_by=order_by.strip() if isinstance(order_by, str) and order_by.strip() else None,
        order_dir=normalized_order_dir,
        limit=normalized_limit,
        offset=normalized_offset,
        explanation=explanation,
        confidence=normalized_confidence,
        aggregations=aggregations,
        distinct=distinct,
        having=having,
        subqueries=subqueries,
    )


def _expand_operator_filter_dicts(filters: dict) -> dict:
    """Convert dict-style comparison values like ``{"operator": ">", "value": 60}``
    into the suffix-key format understood by the engine (e.g. ``age_gt: 60``).
    """
    _OP_TO_SUFFIX: dict[str, str] = {
        ">": "_gt",
        ">=": "_gte",
        "<": "_lt",
        "<=": "_lte",
        "!=": "_ne",
    }
    result: dict = {}
    for key, value in filters.items():
        if (
            isinstance(value, dict)
            and "operator" in value
            and "value" in value
            and len(value) == 2
        ):
            op = value["operator"]
            scalar = value["value"]
            suffix = _OP_TO_SUFFIX.get(op)
            if suffix is not None:
                result[f"{key}{suffix}"] = scalar
            else:
                # operator "=" or unknown — keep key as-is with scalar value
                result[key] = scalar
        else:
            result[key] = value
    return result


def _canonicalize_entity(entity: str, config: NormalizedSchemaConfig) -> str:
    lower = entity.lower()
    if lower in config.entity_aliases:
        return config.entity_aliases[lower]
    if config.entities and entity not in config.entities:
        if config.default_entity:
            return config.default_entity
    return entity


def _canonicalize_field(field: str, config: NormalizedSchemaConfig) -> str:
    lower = field.lower()
    if lower in config.field_aliases:
        return config.field_aliases[lower]
    return field


def _canonicalize_filter_key(key: str, config: NormalizedSchemaConfig) -> str:
    lower = key.lower()
    if lower in config.filter_key_aliases:
        return config.filter_key_aliases[lower]
    return key


def _canonicalize_filter_value(
    key: str, value: Any, config: NormalizedSchemaConfig
) -> str:
    string_value = str(value)
    key_aliases = config.filter_value_aliases.get(key.lower(), {})
    return key_aliases.get(string_value.lower(), string_value)


def _dedupe(items: list[str]) -> list[str]:
    seen: set[str] = set()
    out: list[str] = []
    for item in items:
        if item in seen:
            continue
        seen.add(item)
        out.append(item)
    return out


def _coerce_optional_int(value: Any) -> int | None:
    if value is None:
        return None
    try:
        return int(value)
    except (TypeError, ValueError):
        return None


def extract_raw_sql(raw: str) -> str:
    """Extract a SQL query from raw LLM output, stripping markdown fences and prefixes."""
    # Try fenced code block first
    match = re.search(r"```(?:sql)?\s*(.*?)\s*```", raw, flags=re.S | re.I)
    if match:
        return match.group(1).strip()
    # Strip common prefixes
    for prefix in ("sql query:", "sql:", "query:", "answer:"):
        idx = raw.lower().find(prefix)
        if idx >= 0:
            return raw[idx + len(prefix):].strip()
    return raw.strip()


def extract_raw_graphql(raw: str) -> str:
    """Extract a GraphQL query from raw LLM output, stripping markdown fences."""
    match = re.search(r"```(?:graphql)?\s*(.*?)\s*```", raw, flags=re.S | re.I)
    if match:
        return match.group(1).strip()
    # Find the first opening brace (start of the query)
    brace_start = raw.find("{")
    if brace_start >= 0:
        return raw[brace_start:].strip()
    return raw.strip()


def _load_intent_payload(raw: str) -> dict[str, Any]:
    try:
        payload = json.loads(raw)
    except json.JSONDecodeError:
        payload = None
    if isinstance(payload, dict):
        return payload

    fenced = _extract_fenced_json(raw)
    if fenced is not None:
        try:
            payload = json.loads(fenced)
        except json.JSONDecodeError:
            payload = None
        if isinstance(payload, dict):
            return payload

    object_blob = _extract_first_json_object(raw)
    if object_blob is not None:
        try:
            payload = json.loads(object_blob)
        except json.JSONDecodeError:
            payload = None
        if isinstance(payload, dict):
            return payload

    raise ConstrainedOutputError("LLM output must be valid JSON")


def _extract_fenced_json(raw: str) -> str | None:
    # Non-greedy outer match captures only the FIRST fenced block; delegate to
    # _extract_first_json_object so nested braces are handled correctly instead
    # of the greedy {.*} pattern spanning across multiple code blocks.
    match = re.search(r"```(?:json)?\s*(.*?)\s*```", raw, flags=re.S | re.I)
    if not match:
        return None
    return _extract_first_json_object(match.group(1))


def _extract_first_json_object(raw: str) -> str | None:
    start = raw.find("{")
    if start < 0:
        return None
    state = _JSONScanState(depth=0, in_string=False, escaped=False)
    for idx in range(start, len(raw)):
        ch = raw[idx]
        if _advance_json_scan_state(state, ch) and state.depth == 0:
            return raw[start : idx + 1].strip()
    return None


@dataclass(slots=True)
class _JSONScanState:
    depth: int
    in_string: bool
    escaped: bool


def _advance_json_scan_state(state: _JSONScanState, ch: str) -> bool:
    """Advance brace scanner state.

    Returns True when *ch* was a structural brace outside string context.
    """
    if state.escaped:
        state.escaped = False
        return False
    if ch == "\\":
        state.escaped = True
        return False
    if ch == '"':
        state.in_string = not state.in_string
        return False
    if state.in_string:
        return False
    if ch == "{":
        state.depth += 1
        return True
    if ch == "}":
        state.depth -= 1
        return True
    return False


def _validated_intent_payload(raw: str, language: str) -> dict[str, Any]:
    resolved_language = resolve_language(language)
    if resolved_language != "english":
        raise ConstrainedOutputError(f"Unsupported constraint language '{language}'")
    payload = _load_intent_payload(raw)
    if not isinstance(payload, dict):
        raise ConstrainedOutputError("LLM output must be a JSON object")
    return payload


def _require_non_empty_str(value: Any, message: str) -> str:
    if isinstance(value, str) and value.strip():
        return value
    raise ConstrainedOutputError(message)


def _require_non_empty_str_list(value: Any, message: str) -> list[str]:
    if isinstance(value, list) and all(isinstance(v, str) and v.strip() for v in value):
        return value
    raise ConstrainedOutputError(message)


def _require_dict(value: Any, message: str) -> dict[str, Any]:
    if isinstance(value, dict):
        return value
    raise ConstrainedOutputError(message)


def _require_list(value: Any, message: str) -> list[Any]:
    if isinstance(value, list):
        return value
    raise ConstrainedOutputError(message)


def _require_str(value: Any, message: str) -> str:
    if isinstance(value, str):
        return value
    raise ConstrainedOutputError(message)


def _require_number(value: Any, message: str) -> float:
    if isinstance(value, (int, float)):
        return float(value)
    raise ConstrainedOutputError(message)


def _ensure_optional_str(value: Any, message: str) -> None:
    if value is not None and not isinstance(value, str):
        raise ConstrainedOutputError(message)


def _ensure_optional_scalar(value: Any, message: str) -> None:
    if value is not None and not isinstance(value, (int, float, str)):
        raise ConstrainedOutputError(message)


def _normalize_intent_dict_list(value: Any, required_keys: set[str]) -> list[dict[str, Any]]:
    if not isinstance(value, list):
        return []
    return [
        item
        for item in value
        if isinstance(item, dict) and required_keys.issubset(item.keys())
    ]
